### ISSUE TITLE
Where is ```com.dynatrace.metric``` and ```com.google.common```?

### ISSUE THREAD

**Issue by AlexP-Coding** [dynatrace-oss/opentelemetry-metric-java#24]
I am trying to import this repository as a jar through Eclipse (I do not have gradle) so I can import the ```com.dynatrace.opentelemetry.metric``` package. 

However, both classes within that package (```DynatraceMetricExporter``` and ```Serializer```) require the ```com.dynatrace.metric.util``` package, and one requires the ```com.google.common.base```, ```com.google.common.io```, ```com.google.common.annotations```, and ```com.google.common.collect``` packages.

Where can I find these?

**Comment by arminru** [comment]
Hey @AlexP-Coding!

The `com.dynatrace.metric.util` package is available on Maven Central:
https://repo1.maven.org/maven2/com/dynatrace/metric/util/dynatrace-metric-utils-java/
https://search.maven.org/artifact/com.dynatrace.metric.util/dynatrace-metric-utils-java/
You can find the repository here in case you are interested:
https://github.com/dynatrace-oss/dynatrace-metric-utils-java

If you use a build automation tool like Gradle or Maven, it will pull in all direct and indirect dependencies (like the Google Guava or OpenTelemetry packages) automatically.

**Comment by AlexP-Coding** [comment]
First of all: thank you for pointing me toward the ```com.dynatrace.metric.util``` package - I'd checked for the ```com.google.common.*``` packages but didn't realize ```com.dynatrace.metric.util``` was available on Maven

Secondly, and regarding the remaining dependencies: I am unable to install Gradle at this time, and I've been having considerable issues with Maven, to the point it is preferable for me to download the jars directly.

Do you (or someone reading this) perchance know the artifact id for the google common libraries?

**Comment by arminru** [comment]
If Maven, Gradle, or other tools don't work for you, you could also manually access Maven Central and download the respective jar there: https://repo1.maven.org/maven2/com/dynatrace/metric/util/dynatrace-metric-utils-java/1.6.0/

**Comment by AlexP-Coding** [comment]
Thank you!
I've downloaded both the ```com.dynatrace.metric.util```, ```google-guava```, and ```javax.annotation``` packages and are now able to use the DynatraceMetricExporter as intended.
